name: sozluk_ser_tr_sql_app
description: "Sözlük Uygulaması (SER-TUR SQL Version"

publish_to: 'none'

version: 1.1.8+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  sqflite:
  path_provider:
  path:
  package_info_plus:
  elegant_notification:
  alphabet_list_view:
  lottie:
  provider:
  font_awesome_flutter:
  permission_handler:
  cloud_firestore:
  firebase_core:
  excel: ^2.1.0
  value_layout_builder: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/database/ser_tr_dict.json
    - assets/database/ser_tr_dict.db
