name: sozluk_ser_tr_fb_web_app
description: "A new Flutter project."

publish_to: 'none'

version: 3.0.2+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  package_info_plus:
  elegant_notification:
  alphabet_list_view:
  lottie:
  provider:
  font_awesome_flutter:
  permission_handler:
  cloud_firestore:
  firebase_core:
  excel: ^2.1.0
  value_layout_builder: ^0.5.0
  equatable:
  path_provider:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/database/ser_tr_dict.json