// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTTyvQQN5ddc4wQHTBrrmSaIJ9NVsDkoA',
    appId: '1:68128776175:web:8ffbe0bef80eeff3bb201a',
    messagingSenderId: '68128776175',
    projectId: 'vb-responsive-web-2',
    authDomain: 'vb-responsive-web-2.firebaseapp.com',
    storageBucket: 'vb-responsive-web-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMmFh1S-2lHqmx3EZTnH7AtcHE3L6gSCo',
    appId: '1:68128776175:android:ec357325faa4aa43bb201a',
    messagingSenderId: '68128776175',
    projectId: 'vb-responsive-web-2',
    storageBucket: 'vb-responsive-web-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK-U58kAb3knIITtARNRxzR6hYx9wNIEY',
    appId: '1:68128776175:ios:83ca52c8eccdd662bb201a',
    messagingSenderId: '68128776175',
    projectId: 'vb-responsive-web-2',
    storageBucket: 'vb-responsive-web-2.appspot.com',
    iosBundleId: 'com.example.responsiveWebApp',
  );
}
