name: sozluk_ser_tr_v2
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.8+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core:
  firebase_auth:
  cloud_firestore:
  google_sign_in: ^6.2.1
  google_fonts:
  provider:
  package_info_plus: ^8.0.0
  flag:
  firebase_ui_firestore:
  carousel_slider: ^5.0.0
  path_provider:
  fluttertoast: ^8.2.8
  elegant_notification:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/database/