name: responsive_web_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  easy_dynamic_theme:
  shared_preferences:
  carousel_slider:
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: Electrolize
      fonts:
        - asset: assets/fonts/Electrolize-Regular.ttf
