/// Latin Harfleri
final List<Map<String, String>> fiilListA = [
  {'turkce': "Türkçe Fiil", 'sirpca': 'Sırpça Karşılığı'},
  {'turkce': "Açmak", 'sirpca': 'Otvorati'},
  {'turkce': "Ağlamak", 'sirpca': 'Plakati'},
  {'turkce': "Akmak", 'sirpca': 'Teči'},
  {'turkce': "Almak", 'sirpca': 'Uzimati'},
  {'turkce': "Anlamak", 'sirpca': 'Shvatati'},
  {'turkce': "Anlatmak", 'sirpca': 'Pričati'},
  {'turkce': "Artmak", 'sirpca': 'rasti'},
  {'turkce': "Aşmak", 'sirpca': 'Nadmašivati'},
  {'turkce': "Atmak", 'sirpca': 'Bacati'},
  {'turkce': "Ayırmak", 'sirpca': 'Deliti'},
  {'turkce': "Ayrılmak", 'sirpca': 'Ostavljati / Napuštati'},
  {'turkce': "Azaltmak", 'sirpca': 'Smanjivati'},
];

final List<Map<String, String>> fiilListB = [
  {'turkce': "Türkçe Fiil", 'sirpca': 'Sırpça Karşılığı'},
  {'turkce': "Bağırmak", 'sirpca': 'Vikati'},
  {'turkce': "Bağlamak", 'sirpca': 'Povezivati'},
  {'turkce': "Bakmak", 'sirpca': 'Gledati'},
  {'turkce': "Basmak", 'sirpca': 'Štampati (kitap basmak)'},
  {'turkce': "Başla(t)mak", 'sirpca': 'Početi '},
  {'turkce': "Beklemek", 'sirpca': 'Čekati'},
  {'turkce': "Belirlemek", 'sirpca': 'određivati'},
  {'turkce': "Belirtmek", 'sirpca': 'označavati'},
  {'turkce': "Benzemek", 'sirpca': 'Ličiti'},
  {'turkce': "Bilmek", 'sirpca': 'znati'},
  {'turkce': "Bitirmek", 'sirpca': 'završavati'},
  {'turkce': "Bitmek", 'sirpca': 'Završavati se'},
  {'turkce': "Bulmak", 'sirpca': 'Pronalaziti'},
];

final List<Map<String, String>> fiilListC = [
  {'turkce': "Türkçe Fiil", 'sirpca': 'Sırpça Karşılığı'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
  {'turkce': "---", 'sirpca': '---'},
];
