/// Latin Harfleri
final List<Map<String, String>> fiilListA = [
  {'turkce': "Türkçe Fiil", 'sirpca': 'Sırpça Karşılığı (Imperfekt)'},
  {'turkce': "Açmak", 'sirpca': 'Otvorati'},
  {'turkce': "Ağlamak", 'sirpca': 'Plakati'},
  {'turkce': "Akmak", 'sirpca': 'Teči'},
  {'turkce': "Almak", 'sirpca': 'Uzimati'},
  {'turkce': "Anlamak", 'sirpca': 'Shvatati'},
  {'turkce': "Anlatmak", 'sirpca': 'Pričati'},
  {'turkce': "Artmak", 'sirpca': 'rasti'},
  {'turkce': "Aşmak", 'sirpca': 'Nadmašivati'},
  {'turkce': "Atmak", 'sirpca': 'Bacati'},
  {'turkce': "Ayırmak", 'sirpca': 'Deliti'},
  {'turkce': "Ayrılmak", 'sirpca': 'Ostavljati / Napuštati'},
  {'turkce': "Azaltmak", 'sirpca': 'Smanjivati'},
];

final List<Map<String, String>> fiilListB = [
  {'turkce': "Türkçe Fiil", 'sirpca': 'Sırpça Karşılığı (Imperfekt)'},
  {'turkce': "Bağırmak", 'sirpca': 'Vikati'},
  {'turkce': "Bağlamak", 'sirpca': 'Povezivati'},
  {'turkce': "Bakmak", 'sirpca': 'Gledati'},
  {'turkce': "Basmak", 'sirpca': 'Štampati (kitap basmak)'},
  {'turkce': "Başla(t)mak", 'sirpca': 'Početi '},
  {'turkce': "Beklemek", 'sirpca': 'Čekati'},
  {'turkce': "Belirlemek", 'sirpca': 'određivati'},
  {'turkce': "Belirtmek", 'sirpca': 'označavati'},
  {'turkce': "Benzemek", 'sirpca': 'Ličiti'},
  {'turkce': "Bilmek", 'sirpca': 'znati'},
  {'turkce': "Bitirmek", 'sirpca': 'završavati'},
  {'turkce': "Bitmek", 'sirpca': 'Završavati se'},
  {'turkce': "Bulmak", 'sirpca': 'Pronalaziti'},
];

final List<Map<String, String>> fiilListC = [
  {'turkce': "Türkçe Fiil", 'sirpca': 'Sırpça Karşılığı (Imperfekt)'},
  {'turkce': "Çalışmak", 'sirpca': 'Raditi'},
  {'turkce': "Çalışmak (Ders çalışmak)", 'sirpca': 'Studirati'},
  {'turkce': "Çalmak (Hırsızlık yapmak)", 'sirpca': 'Krasti'},
  {'turkce': "Çalmak (Müzik aleti çalmak)", 'sirpca': 'Svirati'},
  {'turkce': "Çekmek (birini çekmek)", 'sirpca': 'Potezati'},
  {'turkce': "Çevirmek (Dil çevirisi)", 'sirpca': 'Predoviti'},
  {'turkce': "Çevirmek (yön çevirmek)", 'sirpca': 'okretati'},
  {'turkce': "Çıkarmak", 'sirpca': 'Vaditi'},
  {
    'turkce': "Çıkmak (evden çıkmak) / Çıkmak (yeni sayı çıkarmak)",
    'sirpca': 'izlaziti'
  },
];

final List<Map<String, String>> fiilListD = [
  {'turkce': "Türkçe Fiil", 'sirpca': 'Sırpça Karşılığı (Imperfekt)'},
  {'turkce': "Dayanmak (ağrıya/cezaya)", 'sirpca': 'Izdržavati'},
  {'turkce': "Değiştirmek", 'sirpca': 'Mijenjati / Promeniti'},
  {'turkce': "Devam Etmek", 'sirpca': 'Nastavljati'},
  {'turkce': "Dikkat Etmek", 'sirpca': 'Paziti'},
  {'turkce': "Dikkate almak", 'sirpca': 'smatrati'},
  {'turkce': "Dinlemek", 'sirpca': 'Slušati'},
  {'turkce': "Doğurmak", 'sirpca': 'Roditi'},
  {'turkce': "Dolaşmak-", 'sirpca': 'Lutati'},
  {'turkce': "Doldurmak", 'sirpca': 'Puniti'},
  {'turkce': "Döndürmek", 'sirpca': 'Okrenuti (perfekt)'},
  {'turkce': "Durdurmak", 'sirpca': 'Zaustavljati'},
  {'turkce': "Duymak", 'sirpca': 'čuti'},
  {'turkce': "Düşmek", 'sirpca': 'Padati'},
  {'turkce': "Düşünmek", 'sirpca': 'Misliti'},
  {'turkce': "Düzeltmek", 'sirpca': 'Ispravljati'},
];

final List<Map<String, String>> fiilListE = [
  {'turkce': "Türkçe Fiil", 'sirpca': 'Sırpça Karşılığı (Imperfekt)'},
  {'turkce': "Eklemek", 'sirpca': 'Dodavati'},
  {'turkce': "Etkilemek", 'sirpca': 'uticati'},
  {'turkce': "Evlendirmek (erkek)", 'sirpca': 'Ženiti'},
  {'turkce': "Evlendirmek (kadın)", 'sirpca': 'udavati'},
  {'turkce': "Evlenmek (kadın)", 'sirpca': 'udavati se'},
  {'turkce': "Evlenmek (erkek)", 'sirpca': 'Ženiti se'},
];

final List<Map<String, String>> fiilListG = [
  {'turkce': "Türkçe Fiil", 'sirpca': 'Sırpça Karşılığı (Imperfekt)'},
  {'turkce': "Geçirmek / Harcamak", 'sirpca': 'Prodoviti'},
  {'turkce': "Geçmek", 'sirpca': 'Prolaziti'},
  {'turkce': "Geliştirmek", 'sirpca': 'Razvijati'},
  {'turkce': "Gelmek", 'sirpca': 'Dolaziti'},
  {'turkce': "Gerçekleşmek", 'sirpca': 'Ostvarivati'},
  {'turkce': "Gerekmek", 'sirpca': 'Trebati'},
  {'turkce': "Getirmek", 'sirpca': 'Donosti'},
  {'turkce': "Girmek", 'sirpca': 'Ulaziti'},
  {'turkce': "Gitmek", 'sirpca': 'Ići'},
  {'turkce': "Giyinmek", 'sirpca': 'Oblačiti'},
  {'turkce': "Göndermek", 'sirpca': 'Slati'},
  {'turkce': "Görmek", 'sirpca': 'Videti'},
  {'turkce': "Göstermek", 'sirpca': 'Pokazivati'},
  {'turkce': "Götürmek (birini)", 'sirpca': 'Odvodit'},
  {'turkce': "Gülmek", 'sirpca': 'Nasmijavati'},
  {'turkce': "Güldürmek", 'sirpca': 'Nasmejati se'},
];

final List<Map<String, String>> fiilListH = [
  {'turkce': "Türkçe Fiil", 'sirpca': 'Sırpça Karşılığı (Imperfekt)'},
  {'turkce': "Hareket etmek", 'sirpca': 'Kretati se'},
  {'turkce': "Hatırlamak", 'sirpca': 'Pamtiti'},
  {'turkce': "Hatırlatmak", 'sirpca': 'hatırlatmak'},
  {'turkce': "Hazırlamak", 'sirpca': 'pripremati'},
  {'turkce': "Hazır olmak", 'sirpca': 'Spremati se'},
  {'turkce': "Hissetmek", 'sirpca': 'Osjećati'},
  {'turkce': "İçmek", 'sirpca': 'piti'},
  {'turkce': "ifade etmek", 'sirpca': 'izražavati'},
  {'turkce': "İhtiyacı olmak (fiil)", 'sirpca': 'ihtiyaç'},
  {'turkce': "ilerlemek / Hedefe Ulaşmak", 'sirpca': 'nadirati'},
  {'turkce': "İnanmak", 'sirpca': 'Vjerovati'},
  {'turkce': "İncelemek / Sorgulamak", 'sirpca': 'ispitivati'},
  {'turkce': "İnmek", 'sirpca': 'silaziti'},
  {'turkce': "İstemek", 'sirpca': 'Željeti / Htjeti'},
  {'turkce': "İzlemek / Takip Etmek", 'sirpca': 'Slijediti '},
  {'turkce': "İzlemek (birini)", 'sirpca': 'Pratiti'},
  {'turkce': "İzlemek / Bakmak", 'sirpca': 'Gledati'},
];

final List<Map<String, String>> fiilListK = [
  {'turkce': "Türkçe Fiil", 'sirpca': 'Sırpça Karşılığı (Imperfekt)'},
  {'turkce': "Kabul etmek", 'sirpca': 'Prihvaćati'},
  {'turkce': "Kaçmak", 'sirpca': 'Bježati'},
  {'turkce': "Kaldırmak", 'sirpca': 'dizati'},
  {'turkce': "Kalkmak / Uyanmak", 'sirpca': 'ustajati'},
  {'turkce': "Kalmak", 'sirpca': 'Ostati'},
  {'turkce': "Kapatmak", 'sirpca': 'Zatvarati'},
  {'turkce': "Karıştırmak", 'sirpca': 'Miješati se '},
  {'turkce': "Kaybetmek", 'sirpca': 'gubiti'},
  {'turkce': "Kazanmak", 'sirpca': 'zarađivati'},
  {'turkce': "Kesmek", 'sirpca': 'Seći'},
  {'turkce': "Kesmek (Oymak)", 'sirpca': ' izrezivati'},
  {'turkce': "Konuşmak", 'sirpca': 'Govoriti'},
  {'turkce': "Konuşmak (birine anlatmak)", 'sirpca': 'Pričati'},
  {'turkce': "Korkmak", 'sirpca': 'Bojati se'},
  {'turkce': "Korumak", 'sirpca': 'štititi'},
  {'turkce': "Koşmak", 'sirpca': 'trčati'},
  {'turkce': "Koymak", 'sirpca': 'stavljati'},
  {'turkce': "Kullanmak", 'sirpca': 'Koristiti / Upotrebljavati'},
  {'turkce': "Kurmak", 'sirpca': 'Osnovati'},
  {'turkce': "Kurtulmak", 'sirpca': 'Spasiti se'},
];

final List<Map<String, String>> fiilListO = [
  {'turkce': "Türkçe Fiil", 'sirpca': 'Sırpça Karşılığı (Imperfekt)'},
  {'turkce': "Okumak", 'sirpca': 'Čitati'},
  {'turkce': "Olmak", 'sirpca': 'Biti'},
  {'turkce': "Oturmak (fiil)", 'sirpca': 'Sediti'},
  {'turkce': "Oluşturmak", 'sirpca': 'formirati'},
  {'turkce': "Oynamak", 'sirpca': 'igrati'},
  {'turkce': "Ödemek", 'sirpca': 'plaćati'},
  {'turkce': "Öğrenmek / Çalışmak", 'sirpca': 'učiti'},
  {'turkce': "Öğretmek", 'sirpca': 'predavati'},
  {'turkce': "Ölmek", 'sirpca': 'umirati'},
  {'turkce': "Öpmek", 'sirpca': 'ljubiti'},
  {'turkce': "Paylaşmak", 'sirpca': 'deliti'},
  {'turkce': "Pişmek", 'sirpca': 'Peći'},
  {'turkce': "Pişirmek (yemek)", 'sirpca': 'kuvati'},
];

final List<Map<String, String>> fiilListS = [
  {'turkce': "Türkçe Fiil", 'sirpca': 'Sırpça Karşılığı (Imperfekt)'},
  {'turkce': "Sahip Olmak", 'sirpca': 'Imati / Posjedovati'},
  {'turkce': "Sanmak", 'sirpca': 'misliti'},
  {'turkce': "Satın Almak (fiil)", 'sirpca': 'kupovati'},
  {'turkce': "Satmak", 'sirpca': 'Prodavati'},
  {'turkce': "Saymak", 'sirpca': 'brojati'},
  {'turkce': "Seçmek", 'sirpca': 'Odabirati / Birati'},
  {'turkce': "Sevmek", 'sirpca': 'voleti'},
  {'turkce': "Sormak", 'sirpca': 'pitati'},
  {'turkce': "Söylemek / Demek", 'sirpca': 'Reći (perfekt) / kazivati'},
  {'turkce': "Sürdürmek / Devam etmek", 'sirpca': 'nastavljati'},
  {'turkce': "Sürmek (süreç)", 'sirpca': 'Trajati'},
  {'turkce': "Sürmek (araç)", 'sirpca': 'voziti '},
  {'turkce': "Şarkı söylemek", 'sirpca': 'şarkı söylemek'},
  ];

final List<Map<String, String>> fiilListT = [
  {'turkce': "Türkçe Fiil", 'sirpca': 'Sırpça Karşılığı (Imperfekt)'},
  {'turkce': "Tanımak / Bilmek", 'sirpca': 'Poznavati'},
  {'turkce': "Taşımak", 'sirpca': 'Nositi'},
  {'turkce': "Toplamak", 'sirpca': 'Nakupljati'},
  {'turkce': "Toplamak (İşlem)", 'sirpca': 'Sabirati'},
  {'turkce': "Uğraşmak / Başa çıkmak", 'sirpca': 'Baviti se'},
  {'turkce': "Unutmak", 'sirpca': 'Zaboravljati'},
  {'turkce': "Uyumak", 'sirpca': 'Spavati'},
  {'turkce': "Uzanmak / Yatmak", 'sirpca': 'Leći'},
  {'turkce': "Üretmek", 'sirpca': 'Proizvoditi'},
  {'turkce': "Üzmek", 'sirpca': 'Rastuživati'},
  {'turkce': "Üzülmek", 'sirpca': 'Rastuživati se'},
  ];

final List<Map<String, String>> fiilListV = [
  {'turkce': "Türkçe Fiil", 'sirpca': 'Sırpça Karşılığı (Imperfekt)'},
  {'turkce': "Vermek", 'sirpca': 'Davati'},
  {'turkce': "Vurmak", 'sirpca': 'udarati'},
  {'turkce': "Yakalamak", 'sirpca': 'dohvaćati'},
  {'turkce': "Yaklaşmak", 'sirpca': 'Bližiti se'},
  {'turkce': "Yakmak / Aydınlatmak", 'sirpca': 'paliti'},
  {'turkce': "Yanmak", 'sirpca': 'Goreti'},
  {'turkce': "Yapabilmek", 'sirpca': 'moći'},
  {'turkce': "Yapmak", 'sirpca': 'Činiti / Raditi / Praviti'},
  {'turkce': "Yararlanmak / Faydalanmak", 'sirpca': 'iskorištavati'},
  {'turkce': "Yardım Etmek", 'sirpca': 'pomagati'},
  {'turkce': "Yaşamak", 'sirpca': 'živeti'},
  {'turkce': "Yatmak", 'sirpca': 'ležati'},
  {'turkce': "Yaymak", 'sirpca': 'Širiti'},
  {'turkce': "Yayılmak", 'sirpca': 'Širiti se'},
  {'turkce': "Yayınlamak", 'sirpca': 'objavljati'},
  {'turkce': "Yazmak", 'sirpca': 'pisati'},
  {'turkce': "Yemek", 'sirpca': 'jesti'},
  {'turkce': "Yüklemek", 'sirpca': 'opterećivati'},
  {'turkce': "Yükseltmek", 'sirpca': 'podizati'},
  {'turkce': "Yürümek", 'sirpca': 'Hodati'},
];
