// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaiJaqTWubNORXspWm1uZXRxbiEUIQwQI',
    appId: '1:500654422047:web:7f708bd16b21e285457d2a',
    messagingSenderId: '500654422047',
    projectId: 'vb-apps-19a0f',
    authDomain: 'vb-apps-19a0f.firebaseapp.com',
    storageBucket: 'vb-apps-19a0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeHG622xrd8Qcg-a-SHvz5vv5zZj-yk4Q',
    appId: '1:500654422047:android:130680b2ce5d9b17457d2a',
    messagingSenderId: '500654422047',
    projectId: 'vb-apps-19a0f',
    storageBucket: 'vb-apps-19a0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAneEtzGRPZIQTGWPEgp_LuyBPGTgSZSxM',
    appId: '1:500654422047:ios:aaaf837ef429ab0b457d2a',
    messagingSenderId: '500654422047',
    projectId: 'vb-apps-19a0f',
    storageBucket: 'vb-apps-19a0f.appspot.com',
    androidClientId:
        '500654422047-a5a705epieb2v3u6315vntmaprj4dtlb.apps.googleusercontent.com',
    iosClientId:
        '500654422047-8n9rds95cmuhvndee4d7k46qadqqah78.apps.googleusercontent.com',
    iosBundleId: 'com.example.sozlukSerTrV2',
  );
}
