// 📃 <----- alphabet_constants.dart ----->

/// 📌 Latin Harfleri
final List<Map<String, String>> latinAlphabet = [
  {'turkce': "Türkçe Harfler", 'sirpca': 'Sırpça Karşılıkları'},
  {'turkce': "A", 'sirpca': 'A a'},
  {'turkce': "B", 'sirpca': 'B b'},
  {'turkce': "C", 'sirpca': 'Dž dž - C gibi okunur'},
  {'turkce': "C", 'sirpca': 'Đ đ - C gibi okunur'},
  {'turkce': "Ç", 'sirpca': 'Ć ć - Ç gibi okunur'},
  {'turkce': "Ç", 'sirpca': 'Č ć - Ç gibi okunur'},
  {'turkce': "D", 'sirpca': 'D d'},
  {'turkce': "E", 'sirpca': 'E e'},
  {'turkce': "F", 'sirpca': 'F f'},
  {'turkce': "G", 'sirpca': 'G g'},
  {'turkce': "Ğ", 'sirpca': '- -'},
  {'turkce': "H", 'sirpca': 'H h'},
  {'turkce': "I", 'sirpca': '- -'},
  {'turkce': "İ", 'sirpca': 'I i'},
  {'turkce': "J", 'sirpca': 'Ž ž - J gibi okunur'},
  {'turkce': "K", 'sirpca': 'K k'},
  {'turkce': "L", 'sirpca': 'L l'},
  {'turkce': "M", 'sirpca': 'M m'},
  {'turkce': "N", 'sirpca': 'N n'},
  {'turkce': "O", 'sirpca': 'O o'},
  {'turkce': "Ö", 'sirpca': '- -'},
  {'turkce': "P", 'sirpca': 'P p'},
  {'turkce': "R", 'sirpca': 'R r'},
  {'turkce': "S", 'sirpca': 'S s'},
  {'turkce': "Ş", 'sirpca': 'Š š - Ş okunur'},
  {'turkce': "T", 'sirpca': 'T t'},
  {'turkce': "U", 'sirpca': 'U u'},
  {'turkce': "Ü", 'sirpca': 'ju - yu gibi kullanılır ama normalde yok'},
  {'turkce': "V", 'sirpca': 'V v'},
  {'turkce': "Y", 'sirpca': 'J j - Y okunur'},
  {'turkce': "Z", 'sirpca': 'Z z'},
  {'turkce': "TS", 'sirpca': 'C c - ts okunur'},
  {'turkce': "LY", 'sirpca': 'LJ lj - ly okunur'},
  {'turkce': "NY", 'sirpca': 'NJ nj - ny okunur'},
];

/// 📌 Kiril Harfleri
final List<Map<String, String>> kirilAlphabet = [
  {'turkce': "Türkçe Harfler", 'sirpca': 'Sırpça Karşılıkları'},
  {'turkce': "A", 'sirpca': 'A a'},
  {'turkce': "B", 'sirpca': 'Б б'},
  {'turkce': "C", 'sirpca': 'Џ џ - C gibi okunur'},
  {'turkce': "C", 'sirpca': 'Ђ ђ - C gibi okunur'},
  {'turkce': "Ç", 'sirpca': 'Ћ ћ - Ç gibi okunur'},
  {'turkce': "Ç", 'sirpca': 'Ч ч - Ç gibi okunur'},
  {'turkce': "D", 'sirpca': 'Д д'},
  {'turkce': "E", 'sirpca': 'E e'},
  {'turkce': "F", 'sirpca': 'Ф ф'},
  {'turkce': "G", 'sirpca': 'Г г'},
  {'turkce': "Ğ", 'sirpca': '- -'},
  {'turkce': "H", 'sirpca': 'Х х'},
  {'turkce': "I", 'sirpca': '- -'},
  {'turkce': "İ", 'sirpca': 'И и'},
  {'turkce': "J", 'sirpca': 'Ж ж - J gibi okunur'},
  {'turkce': "K", 'sirpca': 'К к'},
  {'turkce': "L", 'sirpca': 'Л л'},
  {'turkce': "M", 'sirpca': 'М м'},
  {'turkce': "N", 'sirpca': 'Н н'},
  {'turkce': "O", 'sirpca': 'О о'},
  {'turkce': "Ö", 'sirpca': '- -'},
  {'turkce': "P", 'sirpca': 'П п'},
  {'turkce': "R", 'sirpca': 'Р р'},
  {'turkce': "S", 'sirpca': 'С с'},
  {'turkce': "Ş", 'sirpca': 'Ш ш - Ş okunur'},
  {'turkce': "T", 'sirpca': 'Т т'},
  {'turkce': "U", 'sirpca': 'U u'},
  {'turkce': "Ü", 'sirpca': 'Ју ју - yu gibi kullanılır ama normalde yok'},
  {'turkce': "V", 'sirpca': 'В в'},
  {'turkce': "Y", 'sirpca': 'J j - Y okunur'},
  {'turkce': "Z", 'sirpca': 'З з'},
  {'turkce': "TS", 'sirpca': 'Ц ц - ts okunur'},
  {'turkce': "LY", 'sirpca': 'Љ љ - ly okunur'},
  {'turkce': "NY", 'sirpca': 'Њ њ - ny okunur'},
];
