// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaiJaqTWubNORXspWm1uZXRxbiEUIQwQI',
    appId: '1:500654422047:web:cb14f6df22100bef457d2a',
    messagingSenderId: '500654422047',
    projectId: 'vb-apps-19a0f',
    authDomain: 'vb-apps-19a0f.firebaseapp.com',
    storageBucket: 'vb-apps-19a0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeHG622xrd8Qcg-a-SHvz5vv5zZj-yk4Q',
    appId: '1:500654422047:android:a9e2afee5dfec2a4457d2a',
    messagingSenderId: '500654422047',
    projectId: 'vb-apps-19a0f',
    storageBucket: 'vb-apps-19a0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAneEtzGRPZIQTGWPEgp_LuyBPGTgSZSxM',
    appId: '1:500654422047:ios:9cbf2d34b32cf2b1457d2a',
    messagingSenderId: '500654422047',
    projectId: 'vb-apps-19a0f',
    storageBucket: 'vb-apps-19a0f.appspot.com',
    iosBundleId: 'com.example.sozlukAppSerTrFbfs',
  );
}
