// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIXG3bC6lxawfrDd2ztEbkA1S2ps3qs30',
    appId: '1:327709201358:web:e6a412557cb4589f55519f',
    messagingSenderId: '327709201358',
    projectId: 'vb-flash-chat-app',
    authDomain: 'vb-flash-chat-app.firebaseapp.com',
    storageBucket: 'vb-flash-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp65P5ac5shKpajzQBcQ8PWChdEaEA4g0',
    appId: '1:327709201358:android:fc2aa760f874e11755519f',
    messagingSenderId: '327709201358',
    projectId: 'vb-flash-chat-app',
    storageBucket: 'vb-flash-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCowHriAVadP9LGacpYIc6OlDtg8D0OxDk',
    appId: '1:327709201358:ios:28cb8ffcf64a64e055519f',
    messagingSenderId: '327709201358',
    projectId: 'vb-flash-chat-app',
    storageBucket: 'vb-flash-chat-app.appspot.com',
    iosBundleId: 'com.example.flashChatApp',
  );
}
