// ignore_for_file: avoid-non-ascii-symbols

class Repository {
  const Repository._();

  static const Map<String, List<String>> animals = {
    'A': [
      'Admiral, indian red',
      'African black crake',
      'African buffalo',
      'African clawless otter',
      'Ant (unidentified)',
      'Armadillo, common long-nosed',
      'Armadillo, nine-banded',
      'Asian lion',
      'Australian sea lion',
      "Azara's zorro",
    ],
    'B': [
      'Baboon, gelada',
      'Baboon, olive',
      'Baboon, savanna',
      'Blackbird, red-winged',
      'Blackbuck',
      'Blacksmith plover',
      'Bushbuck',
    ],
    'C': [
      'Caiman, spectacled',
      'Canada goose',
      'Cape Barren goose',
      'Catfish, blue',
      'Cattle egret',
      'Cobra, cape',
      'Cobra, egyptian',
    ],
    'D': [
      'Dabchick',
      'Dama wallaby',
      'Duck, comb',
      'Duck, mountain',
      'Duiker, gray',
      'Dusky gull',
    ],
    'E': [
      'Eagle owl (unidentified)',
      'Eagle, crowned',
      'Eastern fox squirrel',
      'Eastern white pelican',
      'Eurasian red squirrel',
      'European shelduck',
      'European wild cat',
    ],
    'F': [
      'Fairy penguin',
      'Falcon, peregrine',
      'Falcon, prairie',
      'Fox, cape',
      'Fox, north american red',
      'Frilled dragon',
      'Frilled lizard',
      'Fringe-eared oryx',
      'Frog (unidentified)',
    ],
    'G': [
      'Galah',
      'Galapagos albatross',
      'Galapagos mockingbird',
      'Gaur',
      'Gecko (unidentified)',
      "Grant's gazelle",
      'Gray duiker',
      'Gray heron',
      'Gray rhea',
      'Great white pelican',
      'Greater blue-eared starling',
      'Greater roadrunner',
      'Gull, southern black-backed',
      'Gull, swallow-tail',
    ],
    'H': [
      'Hare, arctic',
      "Hartebeest, coke's",
      'Hawk-headed parrot',
      'Hawk, red-tailed',
      'Hen, sage',
      'Heron, yellow-crowned night',
      'Horned puffin',
      'House crow',
      'Huron',
      'Hyena, striped',
    ],
    'I': [
      'Ibis, glossy',
      'Ibis, puna',
      'Indian red admiral',
      'Indian tree pie',
      'Insect, stick',
    ],
    'J': [
      'Jacana, african',
      'Jackal, black-backed',
      'Jackal, indian',
      'Jaguar',
      'Japanese macaque',
    ],
    'K': [
      'Kaffir cat',
      'Kafue flats lechwe',
      'Kangaroo, eastern grey',
      'Kite, black',
      'Koala',
    ],
    'L': [
      'Langur, common',
      'Lappet-faced vulture',
      'Lapwing, southern',
      'Laughing kookaburra',
      'Lava gull',
      'Least chipmunk',
      'Legaan, ground',
      'Lemur, brown',
      'Long-tailed jaeger',
      'Long-tailed skua',
      'Lorikeet, scaly-breasted',
      'Lourie, grey',
      'Lynx, african',
    ],
    'M': [
      'Macaque, pig-tailed',
      'Macaque, rhesus',
      'Macaw, blue and yellow',
      'Magellanic penguin',
      'Monitor, two-banded',
      'Mule deer',
      'Musk ox',
      'Mynah, indian',
    ],
    'N': [
      'Native cat',
      'Nighthawk, common',
      'Nine-banded armadillo',
      'North American red fox',
      "Nutcracker, clark's",
    ],
    'O': ['Olive baboon', 'Onager', 'Openbill stork', 'Orca', 'Ostrich'],
    'P': [
      'Painted stork',
      'Palm squirrel',
      'Pampa gray fox',
      'Paradoxure',
      'Parakeet, rose-ringed',
      'Peacock, blue',
      'Porcupine, prehensile-tailed',
      'Possum, western pygmy',
      'Potoroo',
      'Prairie falcon',
      'Puma',
      'Puma, south american',
    ],
    'R': [
      'Rabbit, eastern cottontail',
      'Raccoon, common',
      'Racer, american',
      'Red phalarope',
      'Red sheep',
      'Red-billed hornbill',
      'Red-breasted cockatoo',
    ],
    'S': [
      'Sage grouse',
      'Sage hen',
      'Salmon, sockeye',
      'Sambar',
      'Sandgrouse, yellow-throated',
      'Southern boubou',
      'Squirrel, uinta ground',
      'Swamp deer',
    ],

    'Ş': ['Şapka', 'Şişe'],

    'T': [
      'Tailless tenrec',
      'Tapir, brazilian',
      'Tarantula, salmon pink bird eater',
      'Tasmanian devil',
      'Tawny frogmouth',
      'Tayra',
    ],

    'U': ['Uinta ground squirrel'],

    'Ü': ['Üzüm', 'Üzüm Suyu'],

    'V': [
      'Vicuna',
      'Vine snake (unidentified)',
      'Violet-crested turaco',
      'Violet-eared waxbill',
      'Vulture, black',
      'Vulture, king',
      'Vulture, oriental white-backed',
      'Vulture, white-headed',
    ],

    'Y': [
      'Yak',
      'Yellow baboon',
      'Yellow-bellied marmot',
      'Yellow-headed caracara',
      'Yellow-throated sandgrouse',
    ],

    'Z': ['Zebra, plains', 'Zorilla', 'Zorro, common'],
  };
}
